from collections.abc import Awaitable
from typing import Protocol

from her_contracts.telegram import IncomingMessage


class IChatCommands(Protocol):
    def purge(self) -> Awaitable[None]: ...
    def admit(self, data: IncomingMessage) -> Awaitable[bool]: ...
    def step(self, request_id: int) -> Awaitable[bool]: ...
    def recover(self) -> Awaitable[list[int]]: ...
    def forget(self, chat_id: int, user_id: int) -> Awaitable[None]: ...
