from collections.abc import Awaitable
from typing import Protocol

from her_contracts.publications import (
    JobOut,
    ManualPublication,
    Receipt,
    TelegramSend,
)


class ITelegramTransport(Protocol):
    def send(self, data: TelegramSend) -> Awaitable[Receipt]: ...


class IPublicationCommands(Protocol):
    def purge(self) -> Awaitable[None]: ...
    def reserve(self, data: ManualPublication) -> Awaitable[JobOut]: ...
    def deliver(self, job_id: int) -> Awaitable[None]: ...
    def recover(self) -> Awaitable[list[int]]: ...
    def resolve(
        self, job_id: int, actor_id: int, message_id: int | None
    ) -> Awaitable[None]: ...
    def retry(
        self, job_id: int, actor_id: int, confirmed: bool = False
    ) -> Awaitable[str]: ...


class IPublicationQueries(Protocol):
    def job(self, job_id: int) -> Awaitable[JobOut]: ...
    def owned_post(self, message_id: int) -> Awaitable[JobOut]: ...
    def recent(self, limit: int = 10) -> Awaitable[list[JobOut]]: ...
