from collections.abc import Awaitable
from typing import Protocol

from her_contracts.telegram import Admission, IncomingMessage


class IInboxCommands(Protocol):
    def purge(self) -> Awaitable[None]: ...
    def admit(self, data: IncomingMessage) -> Awaitable[Admission]: ...
    def process(self, update_id: int) -> Awaitable[None]: ...
    def recover(self) -> Awaitable[list[int]]: ...


class IMessageHandler(Protocol):
    def handle(self, data: IncomingMessage) -> Awaitable[None]: ...
